CREATE DATABASE IF NOT EXISTS larajwt CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON larajwt.* TO 'root'@'%';

FLUSH PRIVILEGES;
