swagger: "2.0"
# openapi: "3.0.0"
info:
  description: "This is RPG Game Service API Document."
  version: "1.0.0"
  title: "RPG Game Service"
  termsOfService: "https://github.com/user-name/repository-name"
  contact:
    email: "test@example.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3200"
basePath: "/api/v1"
tags:
- name: "gameEnemies"
  description: "GameEnemies infomation"
schemes:
- "https"
- "http"
paths:
  /game/demo/enemies:
    get:
      tags:
      - "gameEnemies"
      summary: "get demo enemy data"
      description: "Returns gameEnemies data"
      produces:
      - "application/json"

      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GameEnemies"
        "404":
          description: "GameEnemies not found"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
        default:
          description: "unsuccessful operation"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
      # security:
      # - authenticaion_key: []
      # - authority_key: []
securityDefinitions:
  authenticaion_key:
    type: "apiKey"
    name: "Authorization"
    in: "header"
  authority_key:
    type: "apiKey"
    name: "X-Auth-Authority"
    in: "header"
definitions:
  GameEnemies:
    type: "array"
    items:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        level:
          type: "integer"
          format: "int64"
        hp:
          type: "integer"
          format: "int64"
        mp:
          type: "integer"
          format: "int64"
        offece:
          type: "integer"
          format: "int64"
        defense:
          type: "integer"
          format: "int64"
        speed:
          type: "integer"
          format: "int64"
        magic:
          type: "integer"
          format: "int64"
  ApiSuccessResponse:
    type: "object"
    properties:
      status:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  ApiErrorResponse:
    type: "object"
    properties:
      status:
        type: "integer"
        format: "int32"
      errors:
        type: "array"
        items:
          type: "string"
      message:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
